language: go

go:
  - "1.15"

env:
  - GO111MODULE=on

install:
  - go get github.com/mattn/goveralls
  - go mod download

script:
  - go test -v -covermode=count -coverprofile=c.out ./errors
  - $GOPATH/bin/goveralls -coverprofile=c.out -service=travis-ci
